### PR TITLE
Pool Loading/Persistence

### PR DESCRIPTION
**Pull request by lsanwick**
BIG CAVEAT: Booster sets provided need to match what the pool was created with.  So `http://localhost:5000/?pool=19&boosters=M13` will work but `http://localhost:5000/?pool=19` will cause a fatal.  This is because we need to load card info for the multiverse ids, but we don't want to fetch all information for all sets every time.

screen shot 2017-03-07 at 10 25 36 pm
screen shot 2017-03-07 at 10 25 30 pm
screen shot 2017-03-07 at 10 25 18 pm

### CODE REVIEW

**Review by danielvinson — COMMENTED** [review]
Hmm I think send_from_directory is too insecure for production.  I'd normally serve static files from nginx but since we're on heroku I'll need to research if there is a better.  Obviously this is fine for developing.

**Review by danielvinson — COMMENTED** [review]
I'm also not certain about storing JSON files.  There are a few better solutions I can think of, such as having a database table which stores these.  I also think we should have a fallback for the file not being there of downloading it from MTG JSON (in the case of a new set or modified data).

**Comment by lsanwick** [comment]
According to this page, `send_from_directory` is the secure way to do this sort of file serving.  http://flask.pocoo.org/docs/0.12/api/#flask.send_from_directory

I'm totally happy to consider improvements for how to serve up set/card info, but I see that as backend implementation, that I, as a glorious front end dev, can hand-wave away. :P

This seemed to be the fastest way to get up and running without problems.  I started down the path of hitting the magicthegathering.io API for individual card data, but firing off 90 AJAX requests when loading a pool was very slow and made the API really unhappy with me.

**Comment by danielvinson** [comment]
Interesting, the documentation does claim that it is fine and I can't really find evidence to the contrary.  Normally the other concern here is speed, but I think a better backend implementation will abstract this away anyway.  The API should load the JSON data and only return what the front-end needs.

I'm going to merge these changes into master so we can get started on the backend changes.

**Pull request merged**
